### ISSUE TITLE
[question] should i use this, or PhoenixAdult?

### ISSUE THREAD

**Issue by PAHelper2** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#1]
Hi!  I'm a long time user of PhoenixAdult, first for Plex, and now Jellyfin.   I have a whole library managed by the current PhoenixAdult plugin.  I have some questions:

* Should I migrate to this one instead? 
* Will PhoenixAdult development continue? 
* What process should I follow to migrate from PhoenixAdult to this plugin, if I should migrate?

Thanks in advance!  Exciting to see what comes.

**Comment by ChalupaBatman69** [comment]
That's totally up to you; Do you prefer solely using the API? Or would you prefer using the actual sites with the API as a backup?

**Comment by PAHelper2** [comment]
Good questions!  I guess my main question is if both plugins are going to be maintained.  And I suppose that's a question for the other developer. :)  Thanks!

**Comment by ChalupaBatman69** [comment]
True, this plugin is maintained by the same guy who maintains PhoenixAdult; 

So use whichever you think works best for you :) I'd say this one works better with the API, whilst the other one focuses on scraping websites with the API as backup.
