### ISSUE TITLE
MetadataApi Token

### ISSUE THREAD

**Issue by xjasonlyu** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#2]
How to acquire metadata api (thePornDB) token?

**Comment by ChalupaBatman69** [comment]
From the API website https://metadataapi.net/

**Comment by xjasonlyu** [comment]
But I can’t login or register. How to create an account then?

**Comment by ChalupaBatman69** [comment]
https://metadataapi.net/register

**Comment by xjasonlyu** [comment]
Registered, but I don’t see any API token related pages😐

**Comment by DirtyRacer1337** [comment]
https://metadataapi.net/user/api-tokens
