### ISSUE TITLE
Is the website down?

### ISSUE THREAD

**Issue by BarryAlanPan** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#22]
I started getting 404 from metadataapi.net since yesterday, is it gonna be a short maintenance?

**Comment by DirtyRacer1337** [comment]
server is down, need to wait when Chalupa is come to restore it

**Comment by BarryAlanPan** [comment]
> server is down, need to wait when Chalupa is come to restore it

You're doing great work! appreciate and big thanks!🙏
