### ISSUE TITLE
API can't response the filename with a '.mov' suffix

### ISSUE THREAD

**Issue by BarryAlanPan** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#24]
As the source code "Providers/Movies.cs" line 96 `searchTitle = searchInfo.Path;`
The filepath(include file name's suffix) is parsed directly to the API handler "Providers/MetadataAPI" and is included in the search url. (line 58 `var url = string.Format(Consts.APISceneSearchURL, searchTitle, oshash);`)
This causing the API server can't recognize the movie with a suffix except from ".mp4" (such as ".mov")

Example:
filename: "woodman-scenes-xxxx-valentina-nappi-xxxx-bed-2-boys.mp4" -> successfully recognized
filename: "woodman-scenes-xxxx-valentina-nappi-xxxx-bed-2-boys.mov" -> null
result from [metadataapi scenes search testing page](https://metadataapi.net/docs#scenes)

Can be fixed by adding a filter like regex to delete the suffix and parse to the API I suggest?

(😢Sorry I didn't request a PR cause I'm not quite familiar with C#)

**Comment by DirtyRacer1337** [comment]
I added this extension to site parser, now need to wait when site would be updated

You can also disable using path in plugin settings

**Comment by DirtyRacer1337** [comment]
Fixed
