### ISSUE TITLE
Trailer Playback Issue

### ISSUE THREAD

**Issue by xjasonlyu** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#26]
Hi there,

When I try to play a trailer, I always get an error of `No compatible streams are currently available. Please try again later or contact your system administrator for details.`.

It's kind of confusing and I thought it might be the trailer video source's issue, so I opened the emby library.db and found the trailer link, then opened it in my browser and it turned out the link is valid. So I wonder why this trailer feature doesn't work even if the trailer url works.

Possible explanation/theory is appreciated.

**Comment by DirtyRacer1337** [comment]
ask jellyfin/emby devs, it's their problem, we only save metadata.

I'm only noticed that my jellyfin have trailers from youtube and none other media host
