### ISSUE TITLE
Jellyfin 10.8 Officially Released - ThePornDB Plugin doesn't work anymore

### ISSUE THREAD

**Issue by zhdenny** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#29]
Jellyfin 10.8 Officially Released - ThePornDB Plugin doesn't work anymore

**Comment by DirtyRacer1337** [comment]
Updated, https://github.com/ThePornDatabase/Jellyfin.Plugin.ThePornDB/releases/tag/latest
