### ISSUE TITLE
Video naming guides

### ISSUE THREAD

**Issue by xjasonlyu** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#3]
What's the recommended naming rules?

**Comment by DirtyRacer1337** [comment]
`SiteName Date Title` for jelly it's can be in path like `SiteName/Date/Title`

**Comment by xjasonlyu** [comment]
So it's basically the seam naming like PhoenixAdult?

**Comment by DirtyRacer1337** [comment]
Yeah, @ChalupaBatman69 can tell you more about naming
