### ISSUE TITLE
Identify Movie on Emby

### ISSUE THREAD

**Issue by nicolobedendo** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#38]
Hi, since TPDB add also the movie i tried to use the identify function with the uid/slug/anything but look only in the scene

**Comment by DirtyRacer1337** [comment]
Yeah, it's scenes only for now

**Comment by DirtyRacer1337** [comment]
It's in [Development Build](https://github.com/ThePornDatabase/Jellyfin.Plugin.ThePornDB/releases/tag/latest)
