### ISSUE TITLE
"Add Collection to Collections" adds Studios as Collections

### ISSUE THREAD

**Issue by widhalmt** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#44]
When I activate the Option "Add Collection to Collections" the plugin will add all the studios on all movies as collections. That might work for adult only DBs but if you mix mainstream media with adult media you'll end up with hundreds of new and useless collections.

Does this work as intended or is this a bug?

Version 1.1.0.6 installed from the Repository for Jellyfin.

**Comment by Darklyter** [comment]
Yes, that's what it's supposed to do.  On a mixed-genre database, I probably wouldn't enable that if I were you.

**Comment by widhalmt** [comment]
Hm, wouldn't it make more sense to use box set instead? As far as I understand, the database lists sites as box sets as well. This way there wouldn't be a collision with other plugins. I experimented a bit with different workarounds but even splitting media into different libraries in the same jellyfin server doesn't work because as far as I understand, collections settings are global.

Or maybe, even better, offer a switch to the configuration with a default to the current behaviour but allow for changing to box set instead of studio to get in sync with other media.

**Comment by DirtyRacer1337** [comment]
jellyfin problem, same happens with performers
