### ISSUE TITLE
emby install Emby.Plugins.ThePornDB.dll do not work 

### ISSUE THREAD

**Issue by whatislove** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#46]
i put Emby.Plugins.ThePornDB.dll into emby plugins package 

sudo chown -R emby:emby  Emby.Plugins.ThePornDB.dll
sudo chmod 777 Emby.Plugins.ThePornDB.*

then reboot emby service ,but it do not appear in emby plugin view.
what am i worong ?

**Comment by DirtyRacer1337** [comment]
send logs
