### ISSUE TITLE
How to search for full movies vs. scenes?

### ISSUE THREAD

**Issue by TheEvilMonkey** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#53]
I have the plug-in installed in Emby and it's working, but appears to be searching for scenes instead of entire movies.  Is there a way to configure it separately?  I know for Plex there are 2 separate bundles, not sure how it works for Emby/JF.

**Comment by DirtyRacer1337** [comment]
Try [dev build](https://github.com/ThePornDatabase/Jellyfin.Plugin.ThePornDB/releases/tag/latest)
