### ISSUE TITLE
Add Emby Plugin Image to package

### ISSUE THREAD

**Issue by jeremymeyers** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#6]
for the directory...here's how https://emby.media/community/index.php?/topic/62511-plugin-image-change/

**Comment by DirtyRacer1337** [comment]
Done in 7cae98750bd0a3ae0b78d5524b1b10df0e039c10, thanks for advice
![image](https://user-images.githubusercontent.com/17379553/118386983-a01a2a00-b645-11eb-8f72-ab5d249100f6.png)
