### ISSUE TITLE
Scenes not showing in Jellyfin + Please provide brief tutorial in README...

### ISSUE THREAD

**Issue by UncertainMongoose** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#67]
Hello everyone! I am new to Jellyfin and this plugin as well. I have tried this as well as the PhoenixAdult plugin but refreshing metadata after enabling either (only one at a time of course) yields no results under any of the tabs.

I have tried naming my scenes like this:
`Studio` - `YYYY-MM-DD` - `Scene Title` (Title as it appears on ThePornDB without special characters)
`Studio` - `YYYY-MM-DD` - `Actor(s), Actor(s)` - `Scene Title`

If any further information is needed, please let me know and I will provide it.

---

P.S. - Please add file naming guidelines and and other information about setup to the README. I would but I don't know the right methods yet...

**Comment by UncertainMongoose** [comment]
I am on Synology NAS running DSM 7.

Jellyfin version: 10.8.10-10  (added through synocommunity package library)

Plugin added via repository link in Jellyfin plugins menu.

**Comment by DirtyRacer1337** [comment]
Try on [latest dev build](https://github.com/ThePornDatabase/Jellyfin.Plugin.ThePornDB/releases/tag/latest)

**Comment by UncertainMongoose** [comment]
> Try on [latest dev build](https://github.com/ThePornDatabase/Jellyfin.Plugin.ThePornDB/releases/tag/latest)

How do I do this on Synology NAS? I don't think I have access to the file structure like I would on Windows...

**Comment by DirtyRacer1337** [comment]
ask jelly devs, you need mount plugin folder, https://jellyfin.org/docs/general/installation/synology/

**Comment by UncertainMongoose** [comment]
I have removed the prior version and added the dev build to my system. The scenes are still not appearing.

**Comment by DirtyRacer1337** [comment]
Did you set `ApiKey` and `PornDB` as library provider?

**Comment by UncertainMongoose** [comment]
I have checked every option containing `PornDB` under Library > Manage Library > Metadata providers but I don't see anywhere to select anything about an `ApiKey`. 

Could you tell me where that setting is located in Jellyfin settings?

**Comment by DirtyRacer1337** [comment]
It's in plugin settings

**Comment by UncertainMongoose** [comment]
Ok I have copied my API token into the `Token` field. 

I have the library type set to `Movies`. Should it be something else?

**Comment by DirtyRacer1337** [comment]
Try to write something simple through `Identify`, it should return something

**Comment by UncertainMongoose** [comment]
To what are you referring? I don't see any text field called Identify.

**Comment by DirtyRacer1337** [comment]
![img](https://github.com/ThePornDatabase/Jellyfin.Plugin.ThePornDB/assets/17379553/bad2bac4-57cd-41a0-bcd9-a98a79abba96)

**Comment by UncertainMongoose** [comment]
![image](https://github.com/ThePornDatabase/Jellyfin.Plugin.ThePornDB/assets/140642754/284b34d9-572f-4446-864b-f9bde7dec8a3)

I do not have that option.

**Comment by DirtyRacer1337** [comment]
On file not library, it's search feature

**Comment by UncertainMongoose** [comment]
There are no files on which to open this context menu because they are not being detected by the plugin...

**Comment by DirtyRacer1337** [comment]
Plugin not detect files it's only provide info
