### ISSUE TITLE
Namer changed metadata URL

### ISSUE THREAD

**Issue by widhalmt** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#68]
Hi,

When I started using Namer ( https://github.com/ThePornDatabase/namer ) it inserted data into .nfo files that were combined by Jellyfin / this plugin to a valid URL. e.g. in the field referencing a scene in metadataapi there was just the ID of the scene. So the plugin could fetch missing or updated metadata.

A new version of namer now prefixes the id (it's even a different id) with `scene/` or `movie/`. Thus the resulting URL is broken and Jellyfin (more exactly this plugin) can't find the corresponding entry in metadataapi.net . 

Could you add an `if` to either use the old URL scheme or use the new one with `scene/` / `movie/`?

**Comment by DirtyRacer1337** [comment]
maybe swap to this id format, need to think about it

**Comment by widhalmt** [comment]
Thanks!

I can imagine, lots of libraries still use the old one in the metadata. So if you switch, maybe it would be good to have some sort of automatic transition. Like, if `scene` or `movie` is missing, fetch the data and rewrite the metadata.

**Comment by DirtyRacer1337** [comment]
in dev build
