### ISSUE TITLE
Naming Convention and Showing multiple of same version

### ISSUE THREAD

**Issue by apperrault** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#69]
I have an odd situation, and a couple of questions.

first, I use Namer, Whisparr, and Stash to "manage" my collection.  I now want to make my collection available to some associates.  I know I can get the plugin to work in Plex, but I would like to use JF for this type of media.

All of the media is named FOLDER\Site\Site - DATE - TITLE - Resolution.EXT

for many of these, it works fine.  but on a bunch of them, it groups all of the ones from the same site as the same title, and then shows like 15 of the same, but in the drop-down, it shows the different names as "Versions" .  I'll post some SFW screenshots to see if this makes sense to anyone.  I have added the API key to the plugin and that works, it's just this combining that is throwing things off

![image](https://github.com/ThePornDatabase/Jellyfin.Plugin.ThePornDB/assets/5666402/6c450eea-f565-40e1-b848-5eb24452ec98)

![image](https://github.com/ThePornDatabase/Jellyfin.Plugin.ThePornDB/assets/5666402/10208024-b9d8-49af-ac94-184925ae2165)

does this make sense?  can anyone help?  I am running JF in docker, and I can easily blow things away and start from scratch if that helps

thanks

**Comment by Druidblack** [comment]
Hi. There was exactly the same problem. These are the features of JF, it groups files into one series based on the name. Put the date of the video at the beginning and jf will stop doing that. Here is an example: 2012-03-24 - Big Tits In Sports - Let's Play Whore - [WEBDL-720p]
