### ISSUE TITLE
Problem with file name recognition

### ISSUE THREAD

**Issue by Druidblack** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#71]
The plugin has a problem with file name recognition in the format (2022-07-03 - Flat 18 - Stephanie Killer Initial Fitness Casting - [WEBDL-720p]).
1. If there are numbers or brackets in the studio name, the plugin does not recognize the video. If you manually delete the studio name during recognition, then the file will be in the database. Example: Fit 18, Family Therapy (Clips4Sale), Beauty 4K, Com 4K
2. The plugin reacts strangely if the video quality is indicated in the file name [WEBDL-540]. It does not recognize it, while if you put [WEBDL-1080] or [WEBDL-480] in the same name, that is, any other other than [WEBDL-540], then the video is recognized.
The plugin used the latest version (from the developer)For an example of errors, I attach a video with an example of work.

https://github.com/ThePornDatabase/Jellyfin.Plugin.ThePornDB/assets/70659424/ecc5a954-586a-454a-9206-38b18e4ffd17

В распознавании имен файлов в формате (2022-07-03 - Flat 18 - Stephanie Killer Initial Fitness Casting - [WEBDL-720p]) есть проблема у плагина. 
1. Если в названии студии есть цифры или скобки, то плагин не распознает видео. Если при распознавании в ручную удалить название студии, то файл находиться в базе данных.  Пример:  Fit 18, Family Therapy (Clips4Sale), Beauty, Cum 4K
2.  Плагин как то странно реагирует, если в названии файла указано качество видео [WEBDL-540]. Он его не распознает, при этом если в том же названии поставить [WEBDL-1080] или [WEBDL-480] тоесть любое другое отличное от [WEBDL-540], то видео распознаеться.
Плагин использовал последней версии (от разработчика)Для примера ошибок прикрепляю видео с примером работы.

**Comment by DirtyRacer1337** [comment]
I guess it's same as #62

I didn't find any problems with `2022-07-03 - Flat 18 - Stephanie Killer Initial Fitness Casting - [WEBDL-720p])`
For search jelly can use filepath, it's in settings, if jelly delete something important
