### ISSUE TITLE
Can't save configuration in Emby

### ISSUE THREAD

**Issue by Michelin452** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#72]
OS: Windows
Emby Server version: 4.8.0.80

When I click save button,the web page just refresh and not save anythings.
Please help,thank you very much

**Comment by WUbo5526** [comment]
一样的问题！期待大佬更新！

**Comment by DirtyRacer1337** [comment]
They changed something in configs and don't even think about backward backward compatibility ...

Better use jellyfin 🤣

**Comment by yubaos** [comment]
QNAP
emby server 4.8.1.0

**Comment by dodobas1** [comment]
emby 服务器 4.8.1.0 一样的问题

**Comment by heihei1634** [comment]
> 一样的问题！期待大佬更新！

最新版本能用了吗？

**Comment by dodobas1** [comment]
> > 一样的问题！期待大佬更新！
> 
> 最新版本能用了

不能

**Comment by DirtyRacer1337** [comment]
well use jelly or old emby 4.7, it's still broken on their side

**Comment by smilejoker365** [comment]
I encountered the same problem. Can the plug-in be adapted to emby 4.8 or above?

**Comment by DumberSoft** [comment]
Apparently Emby is already in version 4.8.3.0, however I see what else they update for Jellyfin in which there would be no update for Emby.

**Comment by DirtyRacer1337** [comment]
Cause of all that theme, it's doesn't work on 4.8

**Comment by smilejoker365** [comment]
https://github.com/MetaSquared/Jellyfin.Plugin.ThePornDB

The plug-in for this project supports emby version 4.8

**Comment by autotypezzzz** [comment]
2024.Apr.13

emby 4.8.3 

I accidently uninstalled it and could not reinstall it, is there any way I can solve this? I've tried to put the .dll file back to the right folder, rerun the server and didn't work.

Already knew that it won't work on current Emby(4.8.x version), but I just can't reinstall it!!!

**Comment by sply94928** [comment]
the same question....how to fix/repair it...

**Comment by fangly-fish** [comment]
@DirtyRacer1337 It's unclear to me from this issue and the other two duplicates .. are you planning on an update to fix compatibility with Emby 4.8? Or is this the end of supporting Emby with this plugin?

@metasquared I don't see any binary releases from your fork. Issues/Discussions aren't open there so I can't ask there. I assume we have to build it ourselves, then? I don't see any instructions to do so.

**Comment by DirtyRacer1337** [comment]
@fangly-fish 4.7 works, ask emby devs to fix it, I found info that old configurations should work, but it's not true. Not going to fix it, emby secondary for me

**Comment by DirtyRacer1337** [comment]
fixed in 7451f5f174056a19e3af461b54aa81b96341f88a, send emby devs my best(not) regards
