### ISSUE TITLE
ThePornDB down?

### ISSUE THREAD

**Issue by traumphase74** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#73]
Great PlugIn but it seems PornDB used to quit?!? Any suggestions? How to use their Data? Can we switch to another distributor?

**Comment by DirtyRacer1337** [comment]
We work on bringing it back, keep an eye on the [Discord](https://discord.gg/CvmFRAAw)

**Comment by DirtyRacer1337** [comment]
It's back
