### ISSUE TITLE
Identifying media doesn't work

### ISSUE THREAD

**Issue by Eymiks** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#75]
Hi,
It seems that video identification doesn't work since the update. Before, all I had to do was copy the studio name and date into the Name field and TPDB would identify the video. I also tried copying the scene id into the "ThePornDB Movie Id" field, but no result.

Jellyfin version 10.8.13
Plugin version 1.2.0.7

**Comment by DirtyRacer1337** [comment]
Check cfg, it might be broken after update, especially providers

`ThePornDB Movie Id` and `ThePornDB JAV Id` are deprecated, now format `endpoint/id`, like `scenes/3`

**Comment by Eymiks** [comment]
I've checked config, everything seems ok. 
Here's what I have in the Identify window. In which field should I put the ID?
![Capture d'écran 2024-03-05 231611](https://github.com/ThePornDatabase/Jellyfin.Plugin.ThePornDB/assets/52335746/161a4217-5e86-46ee-8bb6-59a467122d64)

**Comment by DirtyRacer1337** [comment]
`ThePornDB Movie Id`, forgot jelly naming of that

**Comment by Eymiks** [comment]
It doesn't work, the search results are empty.
![Capture d'écran 2024-03-05 235008](https://github.com/ThePornDatabase/Jellyfin.Plugin.ThePornDB/assets/52335746/c44df8f3-5ccf-4ddb-b551-9296ad86cc21)

**Comment by DirtyRacer1337** [comment]
we doesn't have that scene, https://theporndb.net/scenes/7c9104aa-a104772-83a5-92570b438320 (get with ocr)

**Comment by Eymiks** [comment]
https://theporndb.net/scenes/7c9104aa-a1c3-4772-83a5-92570b438320

**Comment by DirtyRacer1337** [comment]
works for me, again, check everything, api key, provider

**Comment by Eymiks** [comment]
I've got it! Metadata downloaders had been unchecked in the library settings.

Thanks for your time.

**Comment by DirtyRacer1337** [comment]
Yep, as I told, check providers

np
