### ISSUE TITLE
Scenes Endpoint missing scenes/ in url 

### ISSUE THREAD

**Issue by andjones132** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#76]
I installed the latest version of the Jellyfin.Plugin.ThePornDB today and noticed an issue when trying to download the metadata for Scenes. If you just enter the TPDB UUID the Endpoint is "https://theporndb.net/UUID" instead of "https://theporndb.net/scenes/UUID".  I tested this by entering the "scenes/UUID" into the first TPDB field in the Metadata and the Identify screens, and then it would refresh the metadata correctly. 

Also in both the "Identify" and the "Edit Metadata" screens the Scene and Movie fields are not uniquely identified. 

Edit Metadata:
![image](https://github.com/ThePornDatabase/Jellyfin.Plugin.ThePornDB/assets/40303400/641a01e1-0518-49f5-a98d-b7c541d2054d)

Identify:
![image](https://github.com/ThePornDatabase/Jellyfin.Plugin.ThePornDB/assets/40303400/a2a9eac3-37b9-4dbf-8426-aef8397f058b)

**Comment by DirtyRacer1337** [comment]
Feature not a bug, jav and movies id fields deprecated, only one required now
