### ISSUE TITLE
scenes search is null ，but i find page 

### ISSUE THREAD

**Issue by yangxiRespect** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#77]
scenes ：https://theporndb.net/scenes/stuck4k-dont-touch-the-glue-or-youll-get-stuck
use keyword ："Tiny Tyna" "Tiny Tyna" "stuck4k dont touch the glue or youll get stuck"，
Jellyfin plugins search response is null 
page search url ：https://theporndb.net/scenes?page=1&q=Tiny%20Tyna

**Comment by yangxiRespect** [comment]
ThePornDBVersion：1.2.0.7

**Comment by yangxiRespect** [comment]
maybe all search is null ，I can't get any results

**Comment by DirtyRacer1337** [comment]
It's working now

**Comment by DirtyRacer1337** [comment]
Btw restart server, it might be cached
