### ISSUE TITLE
Identifying the same actor as multiple actors in multiple films.

### ISSUE THREAD

**Issue by Victorybiaodi** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#80]
After actors have been duplicated in different movies, multiple actors with the same name are created, making it impossible to see all the movies of a particular actor by searching their name.

**Comment by DirtyRacer1337** [comment]
df4200b80ca93b9e37990c787559b37a1ab91616 should help if it different in db

didn't tested yet
