### ISSUE TITLE
lastest plugin not supported for Jellyfin 10.8.8

### ISSUE THREAD

**Issue by Songhuitang** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#81]
## Information:
- Plugin Version: `1.2.0.7`
- Jellyfin Version:`10.8.8`

## Issue:

- Plugin Status: `NotSupported`
<img width="239" alt="image" src="https://github.com/ThePornDatabase/Jellyfin.Plugin.ThePornDB/assets/12336829/94ef1a11-b619-4994-9eb9-4157ee6f82c3">

- It worked for version `1.1.0.6` before. Due to domain changed, not working anymore.

**Comment by DirtyRacer1337** [comment]
update jellyfin

**Comment by icandura** [comment]
What is the lowest version of jellyfin that this plugin supports?

**Comment by icandura** [comment]
> update jellyfin

What is the lowest version of jellyfin that this plugin supports?

**Comment by DirtyRacer1337** [comment]
https://github.com/ThePornDatabase/Jellyfin.Plugin.ThePornDB/blob/main/Jellyfin.Plugin.ThePornDB/ThePornDB.csproj#L44

**Comment by Songhuitang** [comment]
🌹🌹Could you please kindly keep an baseline version for `10.8.x`  (for mine x = 8)?  It's kind of tough for my NAS(latest version not supported for  current NAS OS) to update the Jellyfin version.

**Comment by DirtyRacer1337** [comment]
should be away to update that version exist more that year

**Comment by icandura** [comment]
> 🌹🌹Could you please kindly keep an baseline version for `10.8.x` (for mine x = 8)? It's kind of tough for my NAS(latest version not supported for current NAS OS) to update the Jellyfin version.

Same as you, the latest version of Jellyfin I can install on my NAS is 10.8.9

**Comment by icandura** [comment]
> 🌹🌹Could you please kindly keep an baseline version for `10.8.x` (for mine x = 8)? It's kind of tough for my NAS(latest version not supported for current NAS OS) to update the Jellyfin version.

Same as you, the latest version of Jellyfin I can install on my NAS is 10.8.9

**Comment by DirtyRacer1337** [comment]
I'm really not understand what's problem to update jelly, where is even multiple docker images

You could build with version you need, change this line, https://github.com/ThePornDatabase/Jellyfin.Plugin.ThePornDB/blob/main/Jellyfin.Plugin.ThePornDB/ThePornDB.csproj#L44
