### ISSUE TITLE
Error updating metadata on Jellyfin v10.9.2

### ISSUE THREAD

**Issue by Tob-Knob** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#84]
Jellyfin: v10.9.2
ThePornDB Plugin: v1.2.0.7

After upgrading to Jellyfin v10.9.2, I noticed the following errors in the logs when updating metadata for scenes.

![image](https://github.com/ThePornDatabase/Jellyfin.Plugin.ThePornDB/assets/124007390/23c6f635-d0ed-42ff-bef5-68b1fe02dc6c)

**Comment by DirtyRacer1337** [comment]
use dev build
