### ISSUE TITLE
Plugin is not updating metadata on Jellyfin v10.9.2

### ISSUE THREAD

**Issue by pdout** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#85]
Since i updated to Jellyfin 10.9.2, i am unable to update metadata.

if I try to manually identify, it shows correct result. But only update images and not metadata (like title, tags, Overview) of scene is updated.

i also tried using Dev Build, But same result.

**Comment by DirtyRacer1337** [comment]
Dev Build works

**Comment by pdout** [comment]
may be i am doing some thing wrong

**Comment by testuser1333** [comment]
same problem with the last update
